name: project_wee
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.7
  go_router: ^14.2.3
  get_it: ^8.0.3
  toastification: ^2.3.0
  qr_flutter: ^4.1.0
  material_dialogs: ^1.1.5
  heroicons: ^0.9.0
  dotted_decoration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
